# Generated by Django 4.2.4 on 2024-01-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='principal',
        ),
        migrations.AddField(
            model_name='principalprofile',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.school'),
        ),
    ]
