# Generated by Django 4.2.4 on 2024-01-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_commissionerprofile_state_school_has_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
